server.port=8081

spring.application.name=campusgigs-api

spring.datasource.url=jdbc:postgresql://localhost:5432/campusgigs
spring.datasource.username=campusgigs
spring.datasource.password=campusgigs123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

campusgigs.jwt.secret=c2VjcmV0LWNhbXB1c2dpZ3MtY2hhdmUtc3VwZXItc2VjcmV0YS1kZS1wZWxvLW1lbm9zLTI1Ni1iaXRz
campusgigs.jwt.expiration-ms=3600000
campusgigs.jwt.type=Bearer

campusgigs.cep.base-url=https://viacep.com.br/ws

